metrics-tracing-context: add Allowlist label filter
metrics-rs/metrics pull request #288
Opened 2022-03-16 21:40 UTC by look

In many metrics system (for example, Datadog) sending all tags will be cost prohibitive if not impossible. Since filtering metrics tags to a small set of allowed tags is a common requirement, add a `LabelFilter` to support this easily.

**Note:** I'm fairly new with Rust, please let me know if there are better ways to implement this.

2022-03-17 00:06 UTC, tobz requested changes
Overall, seems like a reasonable addition!

Left some suggestions just to tighten up the language and API.

2022-03-17 00:06 UTC, tobz commented on metrics-tracing-context/src/label_filter.rs
> +    /// Create a [`Allowlist`] filter with the provide label names.
```suggestion
    /// Create a [`Allowlist`] filter with the provided label names.
```

2022-03-17 00:06 UTC, tobz commented on metrics-tracing-context/src/lib.rs
> +    pub fn allowlist(label_names: &[&str]) -> Self {
A naming and doc comment tweak to make it match the suggestions above:

```suggestion
    /// Creates a new [`TracingContextLayer`] that only allows labels contained
    /// in a predefined list.
    pub fn only_allow<I, S>(allowed: I) -> Self
    where
        I: IntoIterator<Item = S>,
        S: AsRef<str>,
    {
```

2022-03-17 01:06 UTC, look reviewed
Thanks for the feedback!

2022-03-17 01:06 UTC, look commented on metrics-tracing-context/src/label_filter.rs
> +    pub fn new(label_names: &[&str]) -> Allowlist {
Thanks, I was trying to get `IntoIterator` working but was running into some problems!

2022-03-17 01:06 UTC, look commented on metrics-tracing-context/tests/integration.rs
> +    let (_guard, snapshotter) = setup(TracingContextLayer::allowlist(&["env", "service"]));
```suggestion
    let (_guard, snapshotter) = setup(TracingContextLayer::only_allow(&["env", "service"]));
```

2022-03-19 16:59 UTC, tobz approved these changes

2022-03-20 19:37 UTC, merged

2022-03-20 19:37 UTC, tobz commented
Thanks again for your contribution!

2022-05-30 15:28 UTC, tobz commented
Released in `metrics-tracing-context@v0.11.0`.