Fix #289
metrics-rs/metrics pull request #290
Opened 2022-03-18 14:08 UTC by gnuvince

Closes #289 

#289 describes a case when a valid metric name is sanitized (i.e., changed) when it need not be. I added a test to exercise this case and modified the `sanitize_metrics_name` function to pass this test. In terms of approach, I changed from using methods on strings to using a pre-constructed lookup table. The helper functions that were previously used to implement `sanitize_metrics_name` have been moved in the `test` module to act as oracles in the property tests.

2022-03-18 18:13 UTC, tobz commented
@gnuvince Thanks for opening the initial issue and the subsequent PR to fix it.

I think the lookup table approach is a bit too optimized.  I know, this might sound silly, but given the pattern of how an exporter is used -- typically on an interval or polled infrequently -- the lookup table-based approach feels like it's trading far too much in terms of obviousness and readability for what is likely a small improvement in overall performance.

I'd like to a see a more iterative, straightforward approach -- replace the initial character, even if it results in a suboptimal clone, then do the remaining steps -- as a first pass of fixing this issue.

2022-03-18 18:34 UTC, gnuvince commented
How about this version?

2022-03-19 15:21 UTC, tobz requested changes
Looking a lot simpler and straightforward, just one more small tweak.

2022-03-19 15:21 UTC, tobz commented on metrics-exporter-prometheus/src/formatting.rs
> +    return out;
No need for the return here, as the last expression in scope will be used as the return value.

```suggestion
    out
```

2022-04-04 20:42 UTC, tobz approved these changes

2022-04-04 20:42 UTC, merged

2022-05-30 15:24 UTC, tobz commented
Released in `metrics-exporter-prometheus@v0.10.0`.