Add retain functions to Registry
metrics-rs/metrics pull request #461
Opened 2024-03-10 11:26 UTC by kathoum

This adds public functions retain_counters, retain_gauges, retain_histograms, that work like HashMap::retain

2024-03-10 11:35 UTC, kathoum commented
Design-wise, I'm not sure about the choice on the function signature:
`FnMut(&K, &mut S::Counter) -> bool` or `FnMut(&K, &S::Counter) -> bool`

I went with `&mut` because there's already a write lock, so the code has exclusive access to the underlying `S::Counter`, and it shouldn't make much difference in the common case that `Counter = Arc<impl CounterFn>`.

But I understand if we prefer not allowing `mut` access to objects inside the storage.

2024-03-11 20:20 UTC, kathoum commented
PR updated, changed the visitors to accept immutable references

2024-03-13 13:01 UTC, tobz requested changes

2024-03-13 13:01 UTC, tobz commented on metrics-util/src/registry/mod.rs
> +
I think you'd want to copy the assert from lines 512-513 and stick them after adding the `baz` counter, to show that we now have two counters in the registry. After that, do the same thing after the `retain_counters` call to show it goes back down to one counter after it deletes `baz`.

2024-03-16 12:34 UTC, tobz approved these changes
Looks good to me. 👍🏻

2024-03-16 12:35 UTC, merged

2024-03-16 16:30 UTC, tobz commented
Released in `metrics-util@v0.16.3`.

Thanks again for your contribution!